# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SingaporeWeather' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'HandyJSON',                '~> 4.2.0'
  pod 'Alamofire'
  pod 'Cluster'
  pod 'RealmSwift'

  # Pods for SingaporeWeather

end
